//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseDiagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Computer()
        {
            this.Monitors = new HashSet<Monitor>();
            this.Peripheries = new HashSet<Periphery>();
            this.Printers = new HashSet<Printer>();
        }
    
        public int Id { get; set; }
        public string Ip { get; set; }
        public string Name { get; set; }
        public int OS { get; set; }
        public string CPU { get; set; }
        public string GPU { get; set; }
        public int ROM { get; set; }
        public int RAM { get; set; }
        public int NumberCabinet { get; set; }
        public string SerialNumber { get; set; }
        public string InventarNumber { get; set; }
        public int YearRelease { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Monitor> Monitors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Periphery> Peripheries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Printer> Printers { get; set; }
    }
}
