//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseDiagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monitor
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int ScreenSize { get; set; }
        public int ScreenResolutionWidth { get; set; }
        public int ScreenResolutionHeight { get; set; }
        public string SerialNumber { get; set; }
        public string InventarNumber { get; set; }
        public int YearRelease { get; set; }
        public Nullable<int> ComputerId { get; set; }
    
        public virtual Computer Computer { get; set; }
    }
}
