//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseDiagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Server
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string SerialNumber { get; set; }
        public string InventarNumber { get; set; }
        public Nullable<int> PosiitionInServerRack { get; set; }
        public string IpAddress { get; set; }
        public Nullable<int> ServerRackId { get; set; }
        public int OperatingSystem { get; set; }
    
        public virtual ServerRack ServerRack { get; set; }
    }
}
