//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseDiagram
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SudInfoEntities : DbContext
    {
        public SudInfoEntities()
            : base("name=SudInfoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Computer> Computers { get; set; }
        public virtual DbSet<Monitor> Monitors { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Periphery> Peripheries { get; set; }
        public virtual DbSet<Printer> Printers { get; set; }
        public virtual DbSet<Rutoken> Rutokens { get; set; }
        public virtual DbSet<ServerRack> ServerRacks { get; set; }
        public virtual DbSet<Server> Servers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
